services:
  fastapi:
    container_name: fastapi-server-sjchoi
    build:
      context: /labs/docker/images/chat-dev-sjchoi  # ← src의 상위 경로 기준
      dockerfile: src/images/fastapi/Dockerfile
    ports:
      - "48001:8000"
    volumes:
      - /labs/docker/images/chat-dev-sjchoi/src/volumns/fastapi:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
